
server:
  port: 7001
eureka:
  instance:
    hostname:  eureka-7001.com  # Eureka服务端的实例名称
  client:
    register-with-eureka:  false   # 默认会把对应的服务全部注册，false就是向Eureka表明不是一个一个微服务，是一个Eureka中心
    fetch-registry: false    # false表明自己端是注册中心，不需要检索服务
    service-url:
      #   单机版配置defaultZone: 多人版 http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: Server_Center