server:
  port: 8002
spring:
  application:
    name: Scenic-server
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/scenic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  # 日志配置
logging:
  level:
    com.numberone: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# MyBatis
mybatis:
  # 搜索指定包别名
  #  typeAliasesPackage: team.lab.course.domain
  type-aliases-package: com.atguigu.serverprovider.Enity
  # 加载全局的配置文件
  config-location: classpath:mapper/mybatis-config.xml
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*mapper.xml
#配置Eureka中心地址
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用提供自己的ip地址
                            #访问路径可以显示自己的ip
    instance-id: Scenic-server
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

info:
  app.name: Scrapymsg