server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
     # 访问时用自己的ip作为地址
zuul:
  #host:
   # connect-timeout-millis: 60000
    #socket-timeout-millis: 60000
  #ignored-services:  ScenicServer
  routes:
    api-a:
      path: /api/a/**
      serviceId: ServerConsumer
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  #eureka:
   # enabled: false
#feign:
  #hystrix:
   # enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
            thread:
              timeoutInMilliseconds: 6000
