server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com  # Eureka服务端的实例名称
                            #多个Eureka 需要做域名区分和映射
  client:
    register-with-eureka:  false   # 默认会把对应的服务全部注册，false就是向Eureka表明不是一个一个微服务，是一个Eureka中心
    fetch-registry: false    # false表明自己端是注册中心，不需要检索服务
    service-url:
      # defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
         defaultZone: http://eureka7001.com:7001/eureka
