spring:
  application:
    name: ServerConsumer
server:
  port: 8200
eureka:
  client:
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka
      register-with-eureka: true # 阻止客户端在注册中心注册
feign:
  hystrix:
    enabled: false